- name: install dependency packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - git
  tags: [pi-hole]

- name: create pi-hole config directory
  file:
    path: /etc/pihole
    state: directory
    mode: '0755'
  tags: [pi-hole]

- name: create pi-hole clone directory
  file:
    path: "{{ ansible_env.HOME }}/pi-hole"
    state: directory
    mode: '0755'
  tags: [pi-hole]

- name: add pi-hole configuration file
  template:
    src: "{{ role_path }}/templates/setupVars.conf.j2"
    dest: /etc/pihole/setupVars.conf
    owner: root
    group: root
    mode: '0644'
  tags: [pi-hole]

- name: clone pi-hole git repo
  git:
    repo: 'https://github.com/pi-hole/pi-hole.git'
    dest: "{{ ansible_env.HOME }}/pi-hole"
    depth: 1
  tags: [pi-hole]

- name: install pi-hole
  shell: "{{ ansible_env.HOME }}/pi-hole/automated\\ install/basic-install.sh --unattended"
  args:
    creates: /usr/local/bin/pihole
  tags: [pi-hole]

- name: set pihole password
  command: "/usr/local/bin/pihole -a -p {{ pihole_password }}"
  tags: [pi-hole]
